const arr = [
    "The best way to get started is to quit talking and begin doing. - Walt Disney",
    "Don't let yesterday take up too much of today. - Will Rogers",
    "It's not whether you get knocked down, it's whether you get up. - Vince Lombardi",
    "If you are working on something exciting, it will keep you motivated. - Unknown",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "Start where you are. Use what you have. Do what you can.",
    "Small steps each day lead to big changes over time.",
    "Progress, not perfection, wins the long run.",
    "Make today your masterpiece.",
    "Believe you can and you're halfway there.",
    "Dreams don't work unless you do.",
    "Fall seven times, stand up eight.",
    "Your only limit is the one you set yourself.",
    "Action conquers fear.",
    "Work hard in silence; let success make the noise.",
    "The secret of getting ahead is getting started.",
    "Great things never come from comfort zones.",
    "Do something today that your future self will thank you for.",
    "Don't wait for opportunity. Create it.",
    "Consistency compounds into results.",
    "Turn your wounds into wisdom.",
    "Push yourself, because no one else is going to do it for you.",
    "A year from now you'll wish you had started today.",
    "What you do today can improve all your tomorrows.",
    "Doubt kills more dreams than failure ever will.",
    "Be stronger than your strongest excuse.",
    "Focus on the step in front of you, not the whole staircase.",
    "Difficult roads often lead to beautiful destinations.",
    "The only way to achieve the impossible is to believe it is possible.",
    "Turn can't into can and dreams into plans.",
    "Your attitude determines your direction.",
    "Don't limit your challenges. Challenge your limits.",
    "Success is built on a thousand tiny efforts repeated day in and day out.",
    "Be fearless in the pursuit of what sets your soul on fire.",
    "If not now, when? If not you, who?",
    "Greatness begins beyond your comfort zone.",
    "Hustle in silence and let your success be the noise.",
    "You are braver than you believe, stronger than you seem.",
    "Make it happen. Shock everyone.",
    "Chase progress, not approval.",
    "The harder you work, the luckier you get.",
    "Be the energy you want to attract.",
    "Obstacles are those frightful things you see when you take your eyes off the goal.",
    "Your future is created by what you do today, not tomorrow.",
    "Don't stop until you're proud.",
    "If it doesn't challenge you, it won't change you.",
    "Success is the sum of small efforts repeated daily.",
    "Make each day your masterpiece.",
    "Start strong, finish stronger.",
    "Act as if what you do makes a difference. It does.",
    "Create the life you can't wait to wake up to.",
    "The pain you feel today will be the strength you feel tomorrow.",
    "You are the artist of your own life. Don't hand the paintbrush to anyone else.",
    "If you believe it will work out, you'll see opportunities. If you don't, you will see obstacles.",
    "Success usually comes to those who are too busy to be looking for it.",
    "The best view comes after the hardest climb.",
    "A little progress each day adds up to big results.",
    "Make failure your teacher, not your undertaker.",
    "You don't have to be great to start, but you have to start to be great.",
    "The key to success is to start before you're ready.",
    "Replace fear of the unknown with curiosity.",
    "Big journeys begin with small steps.",
    "Be patient. Good things take time.",
    "Rise up and attack the day with enthusiasm.",
    "Shape your future with the choices you make today.",
    "Let your courage be contagious and your confidence inspiring.",
    "Keep going. Each step may get harder, but don't stop. The view is beautiful at the top.",
    "When you feel like quitting, remember why you started.",
    "You were given this life because you are strong enough to live it.",
    "Opportunities don't happen. You create them.",
    "Embrace the pace of your own journey.",
    "Success comes from doing the common things uncommonly well.",
    "Stay focused, stay humble, stay hungry.",
    "Let your actions speak louder than your fears.",
    "The difference between ordinary and extraordinary is that little extra.",
    "Don't count the days; make the days count.",
    "Be the person who decided to go for it.",
    "Work until your idols become your rivals.",
    "The mind is everything. What you think you become.",
    "You don't find willpower; you create it.",
    "Set goals, push yourself, achieve results.",
    "Life rewards action. Do more of it.",
    "Turn your can'ts into cans and your dreams into plans.",
    "The secret to getting results is to start.",
    "Success is a series of small wins.",
    "You'll never always be motivated, so learn to be disciplined.",
    "Create habits that your future self will thank you for.",
    "Don't wait for perfect conditions. Take the shot.",
    "When preparation meets opportunity, success happens.",
    "Make yourself proud by finishing what you start.",
    "Stay persistent — your breakthrough could be one more try away.",
    "Refuse to be average. Let your heart soar as high as it will.",
    "Be the reason someone believes in the goodness of people.",
    "Success is built on consistency, not intensity alone.",
    "Every accomplishment starts with the decision to try.",
    "Choose progress over perfection, every single time.",
    "Keep planting seeds. You will harvest results in time.",
    "Lead with optimism and follow with action.",
    "Let the challenge strengthen, not defeat, you.",
    "Your story is still being written — make it a good one.",
    "Stop wishing. Start doing.",
    "Push past your comfort zone; growth lives there.",
    "Believe in the power of small beginnings.",
    "Your effort today shapes the life of tomorrow.",
    "Stay consistent and the results will follow.",
    "Act with purpose and the rest will fall into place.",
    "Be relentless about your goals but kind to yourself along the way."
    ];
const button = document.querySelector('button');
const quote = document.querySelector("h1")

if (!button || !quote) {
    console.error('Required DOM elements not found: make sure the script runs after the HTML elements are parsed.');
} else {
    button.addEventListener("click", () => {
        const randomIndex = Math.floor(Math.random() * arr.length);
        quote.textContent = arr[randomIndex];
    });
}